spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ibma.j.walker99@gmail.com
    password: rosf mvre rpvu rcxg
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true